changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
      - dependabot
      - github-actions
      - global4ltd-bot
  categories:
    - title: Breaking Changes 🛠
      labels:
        - Semver-Major
        - breaking
    - title: New Features 🎉
      labels:
        - Semver-Minor
        - feature
        - integration
    - title: Bug Fixes
      labels:
        - Semver-Patch
        - bug
    - title: Other Changes
      labels:
        - "*"
